#!/bin/bash

TYPE_SUPPORT_LIST="general|python"

function Usage() {
	echo "Usage: ./create <package-name> [$TYPE_SUPPORT_LIST]"
}

function info() {
	echo "INFO "$*
}
function error() {
	echo "ERROR "$* 1>&2
}

function CheckName () {
	if ! echo $1 | grep -E "^q-(\w|-)+$" > /dev/null 2>&1 ; then
		error "name format error."
		return 2
	fi
	if [ -e $package_name  ]; then
		error "$package_name already exists."
		return 2
	fi

	return 0
}

function CheckType () {
	if echo $1 | grep -E "^($TYPE_SUPPORT_LIST)$" > /dev/null 2>&1 ; then
		return 0
	else
		error "type only support: $TYPE_SUPPORT_LIST"
		return 3
	fi
}

function CopyTemplate () {
	package_name=$1
	package_type=$2
	mkdir $package_name
	cp .template/package.$package_type.spec $package_name/package.spec
}

function main () {
	if [ $# -lt 1 ]; then
		Usage
		exit 1
	fi
	package_name=$1
	package_type=${2:-general}
	CheckName $package_name || exit 2
	CheckType $package_type || exit 3

	CopyTemplate $package_name $package_type

	echo 'done.'
	
}

main $*

# vim: set ts=4:
